### ISSUE TITLE
When using percona with the database cookbook, the mysql chef gem fails to build (Ubuntu 14.04)

### ISSUE THREAD

**Issue by dazwin** [sous-chefs/chef-percona#185]
As per the description - the problem occurs in the 'Monkey patch' provider_mysql_chef_gem.rb:
    chef_gem "mysql" do
        action :install
    end

Debugging through, this step fails because the percona library links to libssl and libcrypto, which are not installed by default.

For now, I've worked around this by adding the following before including the database::mysql recipe:
    package "libssl-dev" do
        action :install
    end

**Comment by asciifaceman** [comment]
I have tried every which way and I am having endless problems with this on 12.04 as well.

The percona cookbooks provider for mysql2 chef gem breaks the percona install as well (mysql wont start and the init file returns no output - only happens when I install the chef gem))

**Comment by damacus** [comment]
As 12.04 is now EOL, and the database cookbook is no more, I'm closing  this slightly old issue ;)
