### ISSUE TITLE
Possibility of adding a new maintainer or transferring repo

### ISSUE THREAD

**Issue by joelhandwell** [sous-chefs/chef-percona#362]
I'm really thankful for the work of @phlipper to lead this repo so far, but it's getting 1 year from the last commit in master, and PRs are waiting to be merged. Among authors of the fork of this repo, @pmichalec, @rll3, @notion, @alindeman can be good candidates of a new maintainer of this repository to keep this repo updated as they recently making commits in forks.

The other option to keep development activity alive would be [transferring ](https://help.github.com/articles/about-repository-transfers/)this repo to a fork such as https://github.com/quadrarubra/chef-percona

Any thoughts?

**Comment by phlipper** [comment]
I am definitely open to assistance maintaining this repo. My daily roles have changed and I don't have the availability at the moment that I once did. I feel bad that it has fallen so far behind, but my limited availability has prevented me from digging out from under the barrage of PRs _(which I appreciate and value immensely)_. I'd like to see this project continue, and assistance with that would be greatly appreciated.

**Comment by djvdorp** [comment]
My vote at this point in time would be for https://github.com/quadrarubra/chef-percona, since it seems to most active and up to date, and I just sent a PR to his for as well for fixing Percona's new APT key. (cc @JohNan)

**Comment by joelhandwell** [comment]
@phlipper @JohNan @rll3 @pmichalec any thoughts on transferring ownership to https://github.com/quadrarubra/chef-percona ?

**Comment by shortdudey123** [comment]
Sous Chefs (github.com/sous-chefs) could take over as well

**Comment by xblitz** [comment]
@phlipper my vote goes to https://github.com/sous-chefs too!

**Comment by xblitz** [comment]
wonder if @sous-chefs were notified here :)   current *maintainer* is looking for help maintaining this cookbook

**Comment by shortdudey123** [comment]
@xblitz i am part of sous-chefs :)

**Comment by xblitz** [comment]
Ok we just need @phlipper to make the next steps,  he is still very active on github (private repos) but seems to ignore this repository :/

**Comment by xblitz** [comment]
@souschef @shortdudey123 maybe a chef-percona2 could be forked from this one since nothing is happening here?

**Comment by devsibwarra** [comment]
I'll put my vote in for @sous-chefs to absorb this into their cookbook collection, if that team and/or @shortdudey123 is still interested in that responsibility.  They're great about testing and updating cookbooks to support the latest Chef changes.  If I'm looking to add desired services / functionality to my Chef environment, I check their repository list before looking elsewhere.

**Comment by damacus** [comment]
hey did we get anywhere with transferring it to sous-chefs or adding a new maintainer? We've had some interest in picking up maintenance from people on slack.

**Comment by swagopopotamus** [comment]
Someone else piping in to support the effort for @shortdudey123 and @sous-chefs to take over. This version bug is becoming a major nuisance.

**Comment by swalberg** [comment]
I'd be happy to contribute if this made it to the @sous-chefs. As others have mentioned the dependencies this is holding is becoming a problem.

**Comment by phlipper** [comment]
Thanks to everyone who has chimed in here, and I apologize for the delay. @shortdudey123, I have some availability to get this transferred to @sous-chefs. Please shoot me an email and let's coordinate a handoff.

**Comment by xblitz** [comment]
though I think we'll need someone else from @sous-chefs  to take this since @shortdudey123 is inactive now .

**Comment by swalberg** [comment]
Hey was just talking to @damacus and he can help with the transferring from the Sous Chefs side.

**Comment by damacus** [comment]
@phlipper I haven't got a copy of your email. If you're on the chef community slack, can you pm me and we'll get this started!

**Comment by mengesb** [comment]
There's a short list of improvements in comparing to quadrarubra fork;

https://github.com/phlipper/chef-percona/compare/master...quadrarubra:master

This is one brief and "easy fix"

**Comment by damacus** [comment]
@phlipper feel free to just hit transfer to the sous-chefs organisation when you get a chance and I'll sort out the rest this end! 

If you want to continue maintaining it, let us know and we'll also sort that out too (by adding you to the sous-chefs organisation).


Thanks! 
Dan

**Comment by phlipper** [comment]
@damacus thanks for chiming in. I just attempted a transfer to @sous-chefs but received the following error:

> You don’t have the permission to create repositories on sous-chefs 

Would you mind adding me as a user of the organization so I can move that over? Please, and thank you!

**Comment by damacus** [comment]
Ah! 

If you make a PR to this we'll get that sorted! 
https://github.com/sous-chefs/terraform-github-org/blob/master/modules/org_membership/main.tf

**Comment by xblitz** [comment]
You might have to do this for him though

**Comment by phlipper** [comment]
Thank you, everyone, for the support and continued nudging to get this over to a new maintainer. This repo is now part of the `sous-chefs` organization. Onward and upward!
