### ISSUE TITLE
Encrypted Data bag problem

### ISSUE THREAD

**Issue by aktarali** [sous-chefs/chef-percona#365]
Hi;

I keep getting the following error:
[2016-10-25T11:39:55+00:00] INFO: Using Percona XtraDB cluster address of: gcomm://
[2016-10-25T11:39:55+00:00] INFO: Unable to load password for root, mysql,fall back to non-encrypted password
[2016-10-25T11:39:55+00:00] INFO: Unable to load password for debian-sys-maint, system,fall back to non-encrypted password

Used following commands to create DB:
knife data bag create passwords
knife data bag from file --secret-file secret_key passwords mysql.json
knife data bag from file --secret-file secret_key passwords system.json

Entries in file are correct as per below;
Mysql.json:
{
  "id": "mysql",
  "root": "test001",
  "backup": "test002",
  "replication": "test003"
}

---

System.json:
{
  "id": "system",
  "idam": "test004"
}

---

Node role attributes:
{
  "name": "percona",
  "description": "Percona Cluster DB role",
  "json_class": "Chef::Role",
  "default_attributes": {
      "percona": {
         "server": {
          "role": [ "cluster" ]
      },
      "cluster": {
        "package": [ "Percona-XtraDB-Cluster-56" ],
        "wsrep_cluster_name": [ "pingfed_SaaSDB_cluster" ],
        "wsrep_sst_receive_interface": [ "eth0" ]
      }
    }
  },
  "override_attributes": {

  },
  "chef_type": "role",
  "run_list": [
        "recipe[percona::cluster_wrapper]"
  ],
  "env_run_lists": {

  }
}

secret_key file exists in /etc/chef/ in the client

**Comment by damacus** [comment]
Hi, 

it looks like this is a problem best discussed on the [Chef community slack ](http://community-slack.chef.io/)
