### ISSUE TITLE
User defined encrypted data bag not being found for password template

### ISSUE THREAD

**Issue by castro1688** [sous-chefs/chef-percona#72]
Instead of using the default data bag passwords, I created a data bag named 'foo'. I could not get the passwords to populate and had other recipes accessing that databag with the supplied key. 

After debugging libraries/passwords.rb for hours, it worked with the following change:

Original

```
  def find_password(key, user, default = nil)
    begin
      # first, let's check for an encrypted data bag and the given key
      passwords = Chef::EncryptedDataBagItem.load(@bag, key)
      # now, let's look for the user password
      password = passwords[user] ### PROBLEM HERE
    rescue
      Chef::Log.info("Using non-encrypted password for #{user}, #{key}")
    end
    # password will be nil if no encrypted data bag was loaded
    # fall back to the attribute on this node
    password ||= default
  end
```

Modified:

```
  def find_password(key, user, default = nil)
    begin
      # first, let's check for an encrypted data bag and the given key
      passwords = Chef::EncryptedDataBagItem.load(@bag, key)
      # now, let's look for the user password
      password = passwords[key][user] # ADDED THE KEY REFERENCE
    rescue
      Chef::Log.info("Using non-encrypted password for #{user}, #{key}")
    end
    # password will be nil if no encrypted data bag was loaded
    # fall back to the attribute on this node
    password ||= default
  end
```

Not sure how this works normally, but when you define your own custom bag, it failed.. or atleast for me it did.

**Comment by damacus** [comment]
Hey, 

thanks for the bug report. As we'll be removing direct data bag and encrypted data bag support from t he cookbook (there will still be a well documented way of doing it like [haproxy does search](https://github.com/sous-chefs/haproxy/blob/master/test/fixtures/cookbooks/test/recipes/config_backend_search.rb),  i.e. not directly baked into the cookbook, but it will easily let you compose resources to perform the same thing. 

Closing as a "won't fix", but please don't ever stop posting issues. We really value the feedback
